### ISSUE TITLE
Sample for AddOnlyPublishedPaths

### ISSUE THREAD

**Issue by florimm** [andreytreyt/yarp-swagger#12]
Im trying to show only published paths, but Im doing wrong something,
If you can provide a sample it would be good.

Thanks

**Comment by fehmianac** [comment]
Hello @florimm,

Would you please share your configuration to check that ?

**Comment by florimm** [comment]
So on the Cluster1 we have 3 endpoints /leads (GET), /leads/test (POST) and /leads/test2 (POST)
As soon as I add the flag AddOnlyPublishedPaths all endpoints are removed
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "ReverseProxy": {
    "Routes": {
      "LeadRoute": {
        "ClusterId": "Cluster1",
        "Match": {
          "Path": "/lead-api/{**catch-all}",
          "Methods": ["GET"]
        },
        "Transforms": [
          {
            "PathPattern": "{**catch-all}"
          }
        ]
      },
      "ProductCatalogRoute": {
        "ClusterId": "Cluster2",
        "Match": {
          "Path": "/product-catalog-api/{**catch-all}"
        },
        "Transforms": [
          {
            "PathPattern": "{**catch-all}"
          }
        ]
      }
    },
    "Clusters": {
      "Cluster1": {
        "Destinations": {
          "Default": {
            "Address": "https://localhost:7043",
            "Swaggers": [
              {
                "PrefixPath": "/lead-api",
                "AddOnlyPublishedPaths": true,
                "Paths": [
                  "/swagger/v1/swagger.json"
                ]
              }
            ]
          }
        }
      },
      "Cluster2": {
        "Destinations": {
          "Default": {
            "Address": "https://localhost:7260",
            "Swaggers": [
              {
                "PrefixPath": "/product-catalog-api",
                "Paths": [
                  "/swagger/v1/swagger.json"
                ]
              }
            ]
          }
        }
      }
    }
  }
}
`

**Comment by fehmianac** [comment]
You are using `{**catch-all}` That's mean you want to open each endpoint to public via gateway.

If you need to strict a some endpoints you should define exact route in proxy config.

AddOnlyPublishedPaths example
`"Match": { "Path": "/proxy-app1/WeatherForecast", "Methods": [ "GET" ] },`
In this case reverse proxy only allow `/proxy-app1/WeatherForecast` endpoint in GET method.


I have also created pull request for a sample.

**Comment by andreytreyt** [comment]
@fehmianac I merged your pull request. Thanks a lot for your efforts 🔥
