### ISSUE TITLE
Add support for code first configuration

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [andreytreyt/yarp-swagger#18]
**Is your feature request related to a problem? Please describe.**
I want to use Yarp-swagger and use code first yarp configuration. Currently this is done by building a custom IProxyConfiguration and adding `RouteConfig` and `ClusterConfig`'s to it programmatically. The problem is that since these are all sealed classes i cannot in any way add the required `Swaggers` Property to the `DestinationConfig` object.

```cs
public static ClusterConfig Cluster() => new()
{
    ClusterId = ClusterId,
    Destinations = new Dictionary<string, DestinationConfig>(StringComparer.OrdinalIgnoreCase)
    {
        {
            "Destination1",
            new MyDestinationConfig()
            {
                Address = "https://localhost:8520",
                Swaggers = new SwaggerDestinationConfig // This doesn't work because DestinationConfig class is sealed
                {
                    
                }
            },
        }
    }
};
```

**Describe the solution you'd like**

I would like some form of support to configure my yarp swagger in code just as i do with my clusters and routes.
I don't believe this is currently possible?

**Describe alternatives you've considered**

I tried extending `DestinationConfig` with a child class but the type is sealed so i cannot touch it. Nor are there any interfaces available for `DestinationConfig`

**Comment by andreytreyt** [comment]
@Joren-Thijs-KasparSolutions The feature was added 🚀 Version [3.3.0](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.3.0) is available. Please star this project ⭐

**Comment by Joren-Thijs-KasparSolutions** [comment]
@andreytreyt wow that was fast Thx! Is there any documentation on how to use it? I looked at the PR but i didn't see any changes to the readme?

Also regarding my star you already had it😉

**Comment by andreytreyt** [comment]
@Joren-Thijs-KasparSolutions I updated README. Now it has [From Code](https://github.com/andreytreyt/yarp-swagger#from-code) section.

Thanks for your issue and your star 👍
