### ISSUE TITLE
Add support (or docs) for modifying downstream/gateway swagger document.

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [andreytreyt/yarp-swagger#20]
**Is your feature request related to a problem? Please describe.**
A common use case is having your API Gateway convert User claims (from a cookie or JWT) to headers for downstream services.
These downstream services have swagger pages that we want to make available in the gateway using this library. 
The problem is that the swagger pages contain headers on every request that the API consumer does not need to worry about since they will only reach them through the Gateway, which handles Authentication and Authorization.

Is it possible to modify either individual swagger pages you forward to? Or to modify the final swagger page that is served on the gateway?

**Describe the solution you'd like**

A feature to modify downstream or the final gateway swagger(s), this can be to remove headers, methods, anything really.
Or if this is already supported, some documentation on how one would use this.

**Describe alternatives you've considered**
There are no alternatives but there is a [similar package](https://github.com/Burgyn/MMLib.SwaggerForOcelot) to this one for the Ocelot Gateway project that has the simple feature of giving you the final swagger as a string which you can then parse however you want and modify before returning it. Something similar would be a great first step.

**Additional context**
Screenshot of the ocelot package example.
<img width="862" alt="image" src="https://github.com/andreytreyt/yarp-swagger/assets/93926934/d489388c-f994-4d63-b3cd-4a4d45a7fb3c">

**Comment by andreytreyt** [comment]
@Joren-Thijs-KasparSolutions Hi there! Sorry for the long answer.

Try to use DocumentFilter
```
public class CustomDocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        // Can modify swaggerDoc
    }
}
```
```
builder.Services.AddSwaggerGen(options =>
{
    ...
    options.DocumentFilter<CustomDocumentFilter>();
});
```
