### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by sander1095** [andreytreyt/yarp-swagger#23]
Hi!

If i look at the csproj, .NET 8 is not supported. 

https://github.com/andreytreyt/yarp-swagger/blob/adcfcf23cb1efdf0c4c318f21a3cdb96bc499e0e/src/Yarp.ReverseProxy.Swagger/Yarp.ReverseProxy.Swagger.csproj#L16C11-L16C11

.NET 8 is now LTS, so that would be great.

Perhaps it could be possible to accept any version of YARP, or any .NET version after yarp 2? That way this library will keep working.

**Comment by andreytreyt** [comment]
[New version](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.5.0) is available now.
