### ISSUE TITLE
Swagger hot-reload 

### ISSUE THREAD

**Issue by tgiachi** [andreytreyt/yarp-swagger#26]
**Is your feature request related to a problem? Please describe.**

Is possible to hot reload swagger definitions like  InMemoryConfigProvider.Update() ?

**Comment by andreytreyt** [comment]
@tgiachi hi there! I don't know how it's possible w/o page reloading if you using appsettings file. You can update a config in appsettings file and after new getting of an openapi scheme you get updated one.

**Comment by mgh9** [comment]
> @tgiachi hi there! I don't know how it's possible w/o page reloading if you using appsettings file. You can update a config in appsettings file and after new getting of an openapi scheme you get updated one.

So is it possible WITH `Page Reloading`? Either `LoadFromConfig` or `LoadFromMemory`?
