### ISSUE TITLE
Tags a absent in gateway swagger

### ISSUE THREAD

**Issue by Ezergil** [andreytreyt/yarp-swagger#27]
**Describe the bug**

direct response from resource server swagger:
<img width="727" alt="Screenshot 2024-01-31 at 14 27 52" src="https://github.com/andreytreyt/yarp-swagger/assets/16032380/a07f815d-5ac6-4e5a-a81b-fbd0421f43fb">
response from gateway:
<img width="665" alt="Screenshot 2024-01-31 at 14 28 04" src="https://github.com/andreytreyt/yarp-swagger/assets/16032380/855e393b-57bc-454e-8178-e4d861efd5e3">

**To Reproduce**

1. Describe controller in resource server (summary)
2. Check swagger.json file on resource server
3. Check swagger.json file on gateway

**Expected behavior**

Description of controllers should be present in gateway swagger

**Comment by andreytreyt** [comment]
[New version](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.6.0) with your changes is available now. Thank you for your contribution.

**Comment by Ezergil** [comment]
Thank you!
