### ISSUE TITLE
Combine multiple swaggers.jsons used by YARP into single one

### ISSUE THREAD

**Issue by MRasztabiga** [andreytreyt/yarp-swagger#32]
@andreytreyt  
Currently final YARP swagger is generated with an assumption that each YARP config's "cluster" element creates a new definition as following:
<img width="480" alt="image" src="https://github.com/andreytreyt/yarp-swagger/assets/15144659/e32b0096-83c5-4e98-8f84-9cb89fc760cd">

This works fine, however i would like to combine actions from all services laying under YARP proxy configuration and expose them as a single Swagger definition (keeping great functionalities like path filtering for each one).

This would probably require some changes in the area of `ReverseProxyDocumentFilter.cs` (or adding a separate filter) and implementation of some kind of simplified OpenApiDocuments merge process.

Would you consider adding support for this?
What are your thoughts?

**Comment by andreytreyt** [comment]
@MRasztabiga Hi! I created [PR](https://github.com/andreytreyt/yarp-swagger/pull/33). Can you pull [branch](https://github.com/andreytreyt/yarp-swagger/tree/issue-32) and check expected feature out with sample projects please. If it'll we be ok I merge the branch and release a new version.

**Comment by andreytreyt** [comment]
@MRasztabiga Hi! I released [3.7.0-alpha](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.7.0-alpha) version. Please check expected feature out and let me know about result and I'll release stable version.

**Comment by andreytreyt** [comment]
@MRasztabiga sounds good! I'll release a stable version.
