### ISSUE TITLE
Reflect transform changes

### ISSUE THREAD

**Issue by jwillmer** [andreytreyt/yarp-swagger#34]
I have a simple proxy that only changes the header name of the underlying API from `tenant`to `customer`.  I wrote a `ITransformFactory` to do the job. How can I reflect these changes in to the swagger? 

```
public bool Build(TransformBuilderContext context, IReadOnlyDictionary<string, string> transformValues)
{
     // note: validation removed to improve readability

    transformValues.TryGetValue("RenameHeader", out var header)
    transformValues.TryGetValue("Set", out var newHeader)
       
        context.AddRequestTransform(transformContext =>
        {
            if (transformContext.ProxyRequest.Headers.TryGetValues(header, out var headerValue))
            {
                // Remove the original header
                transformContext.ProxyRequest.Headers.Remove(header);

                // Add a new header with the same value(s) as the original header
                foreach (var value in headerValue)
                {
                    transformContext.ProxyRequest.Headers.Add(newHeader, value);
                }
            }

            return default;
        });

        return true;
}
```

**Comment by andreytreyt** [comment]
@jwillmer Hello! This library is not supported that feature. "Transform changes" is a feature for YARP. YARP Swagger just displays swagger document of a destination endpoint but you send a request through your proxy always and your transforms work always.

**Comment by jwillmer** [comment]
I already have a working implementation of this feature. I will create a pull request probably this evening. Feel free to review and include it - or not. My use case is solved now :)

**Comment by andreytreyt** [comment]
Wow! Cool! I'll be waiting for it.

**Comment by jwillmer** [comment]
Ah, thank you for the heads up. I missed the notifications. Requested changes applied.

**Comment by andreytreyt** [comment]
@jwillmer Thank you for your contribution! New version [3.8.0](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.8.0) is available.
