### ISSUE TITLE
`ApplySwaggerTransformation()` Throw Argument Null Exception when using Code configuration if `Routes` prop in `ReverseProxyDocumentFilterConfig` is null

### ISSUE THREAD

**Issue by AhmedJoum** [andreytreyt/yarp-swagger#37]
In version 3.8.0 from the package, When using the code configuration:

Missing setting `Routes` property in `ReverseProxyDocumentFilterConfig` cause a Null pointer exception, for earlier versions this wasn't an issue, `Routes` could be null. 

this related to the new function that interduce in `ReverseProxyDocumentFilter` class: `ApplySwaggerTransformation()`

The following is the exception details when applying `ReverseProxyDocumentFilterConfig` with setting only `Clusters` as mentioned in Readme file:

```
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
System.Linq.Enumerable.Where<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
Yarp.ReverseProxy.Swagger.ReverseProxyDocumentFilter.ApplySwaggerTransformation(List<OperationType> operationKeys, KeyValuePair<string, OpenApiPathItem> path, string clusterKey)
Yarp.ReverseProxy.Swagger.ReverseProxyDocumentFilter.Apply(OpenApiDocument swaggerDoc, IReadOnlyDictionary<string, Cluster> clusters)
Yarp.ReverseProxy.Swagger.ReverseProxyDocumentFilter.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
**Suggested Solutions:**
- Update readme file, In "Code configuration"  section, adding the following line inside `ReverseProxyDocumentFilter` initiation:
```
 Routes = GetRoutes().ToDictionary(_ => _.RouteId, _ => _),
```
- On `ApplySwaggerTransformation` make a null validation before iterating through the `Routes` property. 
- Add some summary comments to the properties to identify the purpose of the properties

**Comment by andreytreyt** [comment]
Merged
