### ISSUE TITLE
Swagger Documentation Loading Failure

### ISSUE THREAD

**Issue by Vi2RuS** [andreytreyt/yarp-swagger#45]
**Describe the bug**

The application fails to load Swagger documentation when `Swaggers:Paths` and `Destinations:Address` contain an additional forward slash character.

**To Reproduce**

Add to your `appsettings.json` file

```json
        "Destinations": {
          "Default": {
            "Address": "https://localhost:5101/",  // <-- end with forward slash
            "Swaggers": [
              {
                "PrefixPath": "/proxy-app1",
                "MetadataPath": "/swagger/v1/swagger.json", // <-- start with forward slash
                "Paths": [
                  "/swagger/v1/swagger.json"
                ]
              }
            ]
          }
        }
```

**Screenshots**
![image](https://github.com/user-attachments/assets/457294db-4b35-4cd8-9487-a99db962aeaa)

**Comment by andreytreyt** [comment]
Hello! Thank you for your contribution. New version 3.9.0 is available [here](https://www.nuget.org/packages/Treyt.Yarp.ReverseProxy.Swagger/3.9.0).
