### ISSUE TITLE
Expose only mapped endpoints from downstream API

### ISSUE THREAD

**Issue by mesandeepkr** [andreytreyt/yarp-swagger#9]
Thank you for the nuget it was very much needed. I tried that, and seems all working but it exposes all the endpoints. Do you have something similar to Ocelet to expose only methods that are mentioned in the routing?
For example, the downstream API has 10 endpoints and we want to expose only 2 out of them and the gateway has mapping of only 2 endpoints.

**Comment by andreytreyt** [comment]
> For example, the downstream API has 10 endpoints and we want to expose only 2 out of them and the gateway has mapping of only 2 endpoints.

Can you send an example of your appsettings.json file with routes settings?

**Comment by mesandeepkr** [comment]
Hi @andreytreyt , thank you for your quick turnaround. 
I saw the changes and look good. 

Just two small things
1. Why do we need a new variable "PathFilterRegexPattern". Can't you use the existing one from the YARP configuration?
like either  
```
  "Transforms": [
          {
            "PathPattern": "/Users/{**any}"
          }
        ]
```
 or use the Match path if no Transforms PathPattern is provided?
 ```
"Match": {
          "Path": "/Users/{**any}"
        },
```

2. With the  `"PathFilterRegexPattern": "Users"`, it's displaying all the endpoints with Users as shown in the screenshot below.
But I want to see only `Users`. Seems It's considering it as `Users*` by default which is not good ideally. IMHO `Users` and `Users*` both are different things. YARP also obeys whilecards when explicitly defined not by default. like `{**any}`. 


![image](https://github.com/andreytreyt/yarp-swagger/assets/6063799/5f8c5a2f-cc93-4224-ad03-21a194521e92)

**Comment by mesandeepkr** [comment]
Also, when the pattern doesn't match then also it displays the models. 
for example
`"PathFilterRegexPattern": "Usersaa"` doesn't match with any routing. 

![image](https://github.com/andreytreyt/yarp-swagger/assets/6063799/8bb209bc-bb7b-465d-8401-ab04aed62430)

**Comment by andreytreyt** [comment]
@mesandeepkr thanks for your things :)

1. I decided to use "PathFilterRegexPattern" because I keep it short and simple. In other case I would parse routes. Also you can filter all endpoints with just one expression.
2. You need to use more exact expression in this case.
3. I decided to filter only endpoint yet. Maybe I'll improve it in the future.

You can also send a pull request with your changes.
